/* Spotlight 9 · 1d · Special occasions — 60 words. ★ = must know (20 + 4 cake idioms). */
const WORDS = [
{
"k": "cracker",
"en": "pull a cracker",
"def": "To pull a Christmas paper tube apart so it makes a bang.",
"ru": "хлопнуть рождественскую хлопушку",
"ex": "Crackers are things which we pull at Christmas.",
"g": "Celebrations",
"gru": "Праздники · Ex.1",
"star": true,
"idiom": false
},
{
"k": "exchange",
"en": "exchange a gift/card",
"def": "To give someone something and receive something from them.",
"ru": "обмениваться подарками/открытками",
"ex": "We exchange gifts which we have made ourselves.",
"g": "Celebrations",
"gru": "Праздники · Ex.1",
"star": true,
"idiom": false
},
{
"k": "decorate",
"en": "decorate a tree",
"def": "To put pretty things on a tree.",
"ru": "наряжать ёлку",
"ex": "The children who are decorating the tree look excited.",
"g": "Celebrations",
"gru": "Праздники · Ex.1",
"star": true,
"idiom": false
},
{
"k": "carol",
"en": "sing a carol",
"def": "To sing a traditional Christmas song.",
"ru": "петь рождественскую песню",
"ex": "The children who are singing a carol sound lovely.",
"g": "Celebrations",
"gru": "Праздники · Ex.1",
"star": true,
"idiom": false
},
{
"k": "meal",
"en": "eat a special meal",
"def": "To eat food prepared for an important occasion.",
"ru": "есть праздничное блюдо",
"ex": "We eat a special meal on the day when the family meets.",
"g": "Celebrations",
"gru": "Праздники · Ex.1",
"star": false,
"idiom": false
},
{
"k": "dressup",
"en": "dress up",
"def": "Put on special clothes or a costume.",
"ru": "наряжаться",
"ex": "We dressed up as witches for the carnival.",
"g": "Celebrations",
"gru": "Праздники · Ex.1",
"star": true,
"idiom": false
},
{
"k": "mask",
"en": "wear a mask",
"def": "To cover your face or part of it with a disguise.",
"ru": "носить маску",
"ex": "The boy who is wearing a mask is my brother.",
"g": "Celebrations",
"gru": "Праздники · Ex.1",
"star": true,
"idiom": false
},
{
"k": "parade",
"en": "watch street parades",
"def": "Watch people celebrate as they walk or dance through the streets.",
"ru": "смотреть уличные парады",
"ex": "We watched street parades at the carnival.",
"g": "Celebrations",
"gru": "Праздники · Ex.1",
"star": true,
"idiom": false
},
{
"k": "streamer",
"en": "streamer",
"def": "A long thin strip of coloured paper used at parties.",
"ru": "серпантин",
"ex": "Streamers are decorations which we throw at parties.",
"g": "Celebrations",
"gru": "Праздники · Ex.1",
"star": false,
"idiom": false
},
{
"k": "candles",
"en": "blow out candles",
"def": "To put out candle flames by blowing.",
"ru": "задувать свечи",
"ex": "The girl who is wearing a crown is blowing out the candles.",
"g": "Celebrations",
"gru": "Праздники · Ex.1",
"star": true,
"idiom": false
},
{
"k": "receive",
"en": "receive gifts/cards",
"def": "Get presents or cards from other people.",
"ru": "получать подарки/открытки",
"ex": "I received gifts and cards on my birthday.",
"g": "Celebrations",
"gru": "Праздники · Ex.1",
"star": true,
"idiom": false
},
{
"k": "party",
"en": "have a party",
"def": "Celebrate with a group of people.",
"ru": "устроить праздник/вечеринку",
"ex": "We had a party for my sister.",
"g": "Celebrations",
"gru": "Праздники · Ex.1",
"star": false,
"idiom": false
},
{
"k": "eatcake",
"en": "eat a special cake",
"def": "Eat a sweet cake made for a special occasion.",
"ru": "есть праздничный торт",
"ex": "We ate a special cake at the birthday party.",
"g": "Celebrations",
"gru": "Праздники · Ex.1",
"star": false,
"idiom": false
},
{
"k": "pictures",
"en": "take pictures",
"def": "To make photographs.",
"ru": "фотографировать",
"ex": "The guest who is taking pictures is my cousin.",
"g": "Celebrations",
"gru": "Праздники · Ex.1",
"star": false,
"idiom": false
},
{
"k": "toast",
"en": "make a toast",
"def": "To raise a drink and say good wishes.",
"ru": "произнести тост",
"ex": "The man who is making a toast is the bride's father.",
"g": "Celebrations",
"gru": "Праздники · Ex.1",
"star": true,
"idiom": false
},
{
"k": "excited",
"en": "excited",
"def": "Happy and full of energy about something.",
"ru": "взволнованный, радостный",
"ex": "The boy whose birthday is today is excited.",
"g": "Feelings",
"gru": "Чувства · Ex.2–3",
"star": true,
"idiom": false
},
{
"k": "nervous",
"en": "nervous",
"def": "Worried about something that may happen.",
"ru": "нервничающий",
"ex": "I felt nervous before speaking at the party.",
"g": "Feelings",
"gru": "Чувства · Ex.2–3",
"star": true,
"idiom": false
},
{
"k": "thrilled",
"en": "thrilled",
"def": "Extremely pleased and excited.",
"ru": "в восторге",
"ex": "The guests who won the game were thrilled.",
"g": "Feelings",
"gru": "Чувства · Ex.2–3",
"star": true,
"idiom": false
},
{
"k": "enthusiastic",
"en": "enthusiastic",
"def": "Very interested and eager to do something.",
"ru": "полный энтузиазма",
"ex": "The guests who are planning the games are enthusiastic.",
"g": "Feelings",
"gru": "Чувства · Ex.2–3",
"star": false,
"idiom": false
},
{
"k": "surprised",
"en": "surprised",
"def": "Feeling that something unexpected has happened.",
"ru": "удивлённый",
"ex": "The girl whose friends arrived early was surprised.",
"g": "Feelings",
"gru": "Чувства · Ex.2–3",
"star": false,
"idiom": false
},
{
"k": "impatient",
"en": "impatient",
"def": "Unable to wait calmly.",
"ru": "нетерпеливый",
"ex": "The guests who are waiting for the cake are getting impatient.",
"g": "Feelings",
"gru": "Чувства · Ex.2–3",
"star": true,
"idiom": false
},
{
"k": "happy",
"en": "happy",
"def": "Feeling good and pleased.",
"ru": "счастливый, радостный",
"ex": "I felt happy at my birthday party.",
"g": "Feelings",
"gru": "Чувства · Ex.2–3",
"star": false,
"idiom": false
},
{
"k": "embarrassed",
"en": "embarrassed",
"def": "Feeling uncomfortable because people notice a mistake or something personal.",
"ru": "смущённый",
"ex": "I felt embarrassed when everyone sang to me.",
"g": "Feelings",
"gru": "Чувства · Ex.2–3",
"star": true,
"idiom": false
},
{
"k": "proud",
"en": "proud",
"def": "Pleased because you or someone you care about has done something well.",
"ru": "гордый",
"ex": "My parents felt proud at my graduation.",
"g": "Feelings",
"gru": "Чувства · Ex.2–3",
"star": true,
"idiom": false
},
{
"k": "wedding",
"en": "wedding reception",
"def": "A celebration with guests after a wedding ceremony.",
"ru": "свадебный приём",
"ex": "The hotel where the wedding reception took place was lovely.",
"g": "Parties & wishes",
"gru": "Праздники и пожелания · Ex.3",
"star": true,
"idiom": false
},
{
"k": "graduation",
"en": "graduation party",
"def": "A party to celebrate finishing school or university.",
"ru": "выпускной вечер",
"ex": "A graduation party is an event where students celebrate their success.",
"g": "Parties & wishes",
"gru": "Праздники и пожелания · Ex.3",
"star": true,
"idiom": false
},
{
"k": "returns",
"en": "Many happy returns!",
"def": "A birthday wish for many more happy years.",
"ru": "С днём рождения!",
"ex": "Many happy returns to the girl whose birthday is today!",
"g": "Parties & wishes",
"gru": "Праздники и пожелания · Ex.3",
"star": true,
"idiom": false
},
{
"k": "anniversary",
"en": "Happy anniversary!",
"def": "A wish for the yearly date of an important event.",
"ru": "С годовщиной!",
"ex": "Happy anniversary to the couple who got married here!",
"g": "Parties & wishes",
"gru": "Праздники и пожелания · Ex.3",
"star": false,
"idiom": false
},
{
"k": "congrats",
"en": "congratulations",
"def": "Words used to show happiness about someone's success.",
"ru": "поздравления",
"ex": "Congratulations to the students who have graduated!",
"g": "Parties & wishes",
"gru": "Праздники и пожелания · Ex.3",
"star": true,
"idiom": false
},
{
"k": "season",
"en": "Season's greetings!",
"def": "Good wishes during the Christmas and New Year season.",
"ru": "С праздниками!",
"ex": "Season's greetings to everyone who has helped us!",
"g": "Parties & wishes",
"gru": "Праздники и пожелания · Ex.3",
"star": false,
"idiom": false
},
{
"k": "all-best",
"en": "all the best",
"def": "A friendly wish for success or happiness.",
"ru": "всего хорошего",
"ex": "All the best to everyone who is taking part!",
"g": "Parties & wishes",
"gru": "Праздники и пожелания · Ex.3",
"star": false,
"idiom": false
},
{
"k": "newyear",
"en": "Happy New Year!",
"def": "A greeting at the start of a new year.",
"ru": "С Новым годом!",
"ex": "Happy New Year to everyone who is celebrating!",
"g": "Parties & wishes",
"gru": "Праздники и пожелания · Ex.3",
"star": false,
"idiom": false
},
{
"k": "hotcakes",
"en": "sell like hot cakes",
"def": "To sell very quickly and in large numbers.",
"ru": "продаваться нарасхват",
"ex": "The tickets which we printed are selling like hot cakes.",
"g": "Cake idioms",
"gru": "Идиомы с cake · Ex.4",
"star": true,
"idiom": true
},
{
"k": "icing",
"en": "the icing on the cake",
"def": "An extra good thing that makes something good even better.",
"ru": "приятное дополнение к хорошему",
"ex": "The surprise party was the icing on the cake.",
"g": "Cake idioms",
"gru": "Идиомы с cake · Ex.4",
"star": true,
"idiom": true
},
{
"k": "piece",
"en": "a piece of cake",
"def": "Something very easy to do.",
"ru": "проще простого",
"ex": "The game which we played was a piece of cake.",
"g": "Cake idioms",
"gru": "Идиомы с cake · Ex.4",
"star": true,
"idiom": true
},
{
"k": "havecake",
"en": "have your cake and eat it",
"def": "To want two good things that cannot both happen.",
"ru": "и съесть пирог, и сохранить его",
"ex": "He wants to have his cake and eat it: keep the cake and eat it too.",
"g": "Cake idioms",
"gru": "Идиомы с cake · Ex.4",
"star": true,
"idiom": true
},
{
"k": "coming",
"en": "coming-of-age",
"def": "The time when a young person becomes an adult.",
"ru": "достижение взрослого возраста",
"ex": "A coming-of-age celebration marks the time when you become an adult.",
"g": "Sweet Sixteen",
"gru": "Слова текста · Ex.5",
"star": false,
"idiom": false
},
{
"k": "teenage",
"en": "teenage",
"def": "Related to ages thirteen to nineteen.",
"ru": "подростковый",
"ex": "The club where we meet organises teenage parties.",
"g": "Sweet Sixteen",
"gru": "Слова текста · Ex.5",
"star": false,
"idiom": false
},
{
"k": "fuss",
"en": "fuss",
"def": "More worry or activity than is needed.",
"ru": "суета, суматоха",
"ex": "The cake which arrived late caused a lot of fuss.",
"g": "Sweet Sixteen",
"gru": "Слова текста · Ex.5",
"star": false,
"idiom": false
},
{
"k": "senior",
"en": "senior year",
"def": "The last year at a school or college.",
"ru": "выпускной год",
"ex": "This is the year when she finishes school: her senior year.",
"g": "Sweet Sixteen",
"gru": "Слова текста · Ex.5",
"star": false,
"idiom": false
},
{
"k": "junior",
"en": "junior high",
"def": "A US school for students between elementary and high school.",
"ru": "средняя школа в США",
"ex": "The school where she studies is a junior high school.",
"g": "Sweet Sixteen",
"gru": "Слова текста · Ex.5",
"star": false,
"idiom": false
},
{
"k": "theme",
"en": "theme",
"def": "The main idea that connects an event's decorations and activities.",
"ru": "тема",
"ex": "The theme which we chose was pirates.",
"g": "Sweet Sixteen",
"gru": "Слова текста · Ex.5",
"star": false,
"idiom": false
},
{
"k": "budget",
"en": "budget",
"def": "The amount of money available to spend.",
"ru": "бюджет",
"ex": "Our budget determines which party we can afford.",
"g": "Sweet Sixteen",
"gru": "Слова текста · Ex.5",
"star": false,
"idiom": false
},
{
"k": "band",
"en": "band",
"def": "A group of people who play music together.",
"ru": "музыкальная группа",
"ex": "The band which is playing tonight is fantastic.",
"g": "Sweet Sixteen",
"gru": "Слова текста · Ex.5",
"star": false,
"idiom": false
},
{
"k": "rich",
"en": "rich",
"def": "Containing a lot of butter, cream or similar ingredients.",
"ru": "жирный, насыщенный о еде",
"ex": "The cake which they served was rich and delicious.",
"g": "Sweet Sixteen",
"gru": "Слова текста · Ex.5",
"star": false,
"idiom": false
},
{
"k": "flowers",
"en": "flower arrangement",
"def": "Flowers placed together in an attractive way.",
"ru": "цветочная композиция",
"ex": "The flower arrangement which is on the table looks beautiful.",
"g": "Sweet Sixteen",
"gru": "Слова текста · Ex.5",
"star": false,
"idiom": false
},
{
"k": "casual",
"en": "casual",
"def": "Relaxed and not formal.",
"ru": "повседневный, неофициальный",
"ex": "I like parties where we can wear casual clothes.",
"g": "Sweet Sixteen",
"gru": "Слова текста · Ex.5",
"star": false,
"idiom": false
},
{
"k": "limo",
"en": "limousine",
"def": "A large, comfortable, expensive car.",
"ru": "лимузин",
"ex": "The limousine which took us to the party was enormous.",
"g": "Sweet Sixteen",
"gru": "Слова текста · Ex.5",
"star": false,
"idiom": false
},
{
"k": "specific",
"en": "specific",
"def": "One particular thing, not a general idea.",
"ru": "конкретный, определённый",
"ex": "I want the specific balloon which is gold.",
"g": "Sweet Sixteen",
"gru": "Слова текста · Ex.5",
"star": false,
"idiom": false
},
{
"k": "unique",
"en": "unique",
"def": "The only one of its kind.",
"ru": "уникальный",
"ex": "The costume which she made is unique.",
"g": "Sweet Sixteen",
"gru": "Слова текста · Ex.5",
"star": false,
"idiom": false
},
{
"k": "happening",
"en": "happening",
"def": "An event, especially something unusual or interesting.",
"ru": "событие, происшествие",
"ex": "The party was a happening which everyone remembered.",
"g": "Sweet Sixteen",
"gru": "Слова текста · Ex.5",
"star": false,
"idiom": false
},
{
"k": "formal",
"en": "formal",
"def": "Following serious rules about clothes and behaviour.",
"ru": "официальный",
"ex": "A reception where guests wear suits is formal.",
"g": "Sweet Sixteen",
"gru": "Слова текста · Ex.5",
"star": false,
"idiom": false
},
{
"k": "informal",
"en": "informal",
"def": "Friendly and relaxed, without strict rules.",
"ru": "неофициальный",
"ex": "I prefer informal parties where everyone feels comfortable.",
"g": "Sweet Sixteen",
"gru": "Слова текста · Ex.5",
"star": false,
"idiom": false
},
{
"k": "strict",
"en": "strict",
"def": "Making people follow rules carefully.",
"ru": "строгий",
"ex": "The teacher who checks our costumes is strict.",
"g": "Sweet Sixteen",
"gru": "Слова текста · Ex.5",
"star": false,
"idiom": false
},
{
"k": "depend",
"en": "depend on",
"def": "To be decided or affected by something.",
"ru": "зависеть от",
"ex": "The place where we celebrate depends on the weather.",
"g": "Sweet Sixteen",
"gru": "Слова текста · Ex.5",
"star": false,
"idiom": false
},
{
"k": "rely",
"en": "rely on",
"def": "To trust someone or something to help you.",
"ru": "полагаться на",
"ex": "The friend who is organising the music relies on me.",
"g": "Sweet Sixteen",
"gru": "Слова текста · Ex.5",
"star": false,
"idiom": false
},
{
"k": "rest",
"en": "rest on",
"def": "To be supported by something.",
"ru": "опираться на",
"ex": "The success of a party can rest on the people who organise it.",
"g": "Sweet Sixteen",
"gru": "Слова текста · Ex.5",
"star": false,
"idiom": false
},
{
"k": "base",
"en": "base on",
"def": "To use something as the starting point for an idea.",
"ru": "основывать на",
"ex": "We base our party theme on a film which we love.",
"g": "Sweet Sixteen",
"gru": "Слова текста · Ex.5",
"star": false,
"idiom": false
},
{
"k": "plan",
"en": "plan a party",
"def": "To decide how a party will happen.",
"ru": "планировать вечеринку",
"ex": "The friends who are planning the party have chosen a theme.",
"g": "Sweet Sixteen",
"gru": "Слова текста · Ex.5",
"star": false,
"idiom": false
},
{
"k": "mostly",
"en": "mostly",
"def": "For the largest part; mainly.",
"ru": "главным образом",
"ex": "The guests who came were mostly our classmates.",
"g": "Sweet Sixteen",
"gru": "Слова текста · Ex.5",
"star": false,
"idiom": false
}
];
