/* Spotlight 7 · 2a · Bookworms — 60 words. ★ = must know (genres + the words of the text). */
const WORDS = [
{
"k": "adventure",
"en": "adventure story",
"def": "An exciting story about a journey.",
"ru": "приключенческий рассказ",
"ex": "A boy wrote an adventure story about a flying sandwich.",
"g": "Genres",
"gru": "Жанры · Ex.1",
"star": true,
"idiom": false
},
{
"k": "science-fiction",
"en": "science fiction",
"def": "Stories about the future or space.",
"ru": "научная фантастика",
"ex": "A robot read science fiction on the moon.",
"g": "Genres",
"gru": "Жанры · Ex.1",
"star": true,
"idiom": false
},
{
"k": "drama",
"en": "drama",
"def": "A serious play with strong feelings.",
"ru": "драма",
"ex": "The drama was about a lost robot.",
"g": "Genres",
"gru": "Жанры · Ex.1",
"star": true,
"idiom": false
},
{
"k": "mystery",
"en": "mystery",
"def": "A story about a crime or a strange event.",
"ru": "детектив; загадка",
"ex": "My friend wrote a mystery about a missing sandwich.",
"g": "Genres",
"gru": "Жанры · Ex.1",
"star": true,
"idiom": false
},
{
"k": "humorous-story",
"en": "humorous story",
"def": "A funny story that makes you laugh.",
"ru": "юмористический рассказ",
"ex": "A girl wrote a humorous story about a dancing robot.",
"g": "Genres",
"gru": "Жанры · Ex.1",
"star": true,
"idiom": false
},
{
"k": "biography",
"en": "biography",
"def": "A person’s life story, written by another person.",
"ru": "биография",
"ex": "My brother read a biography of a brave explorer.",
"g": "Genres",
"gru": "Жанры · Ex.1",
"star": true,
"idiom": false
},
{
"k": "author",
"en": "author",
"def": "A person who writes books or stories.",
"ru": "автор; писатель",
"ex": "The author created a flying sandwich.",
"g": "Text",
"gru": "Слова текста · Ex.2–4",
"star": true,
"idiom": false
},
{
"k": "character",
"en": "character",
"def": "A person or creature in a story.",
"ru": "персонаж; герой",
"ex": "She created a character with a talking backpack.",
"g": "Text",
"gru": "Слова текста · Ex.2–4",
"star": true,
"idiom": false
},
{
"k": "g0",
"en": "amazing",
"def": "Very surprising or impressive.",
"ru": "удивительный",
"ex": "The amazing cat flew to the moon.",
"g": "Text",
"gru": "Слова текста · Ex.2–4",
"star": true,
"idiom": false
},
{
"k": "g1",
"en": "appearance",
"def": "How someone looks.",
"ru": "внешний вид",
"ex": "The robot checked its appearance in a mirror.",
"g": "Text",
"gru": "Слова текста · Ex.2–4",
"star": true,
"idiom": false
},
{
"k": "g2",
"en": "bookworm",
"def": "Someone who reads a lot of books.",
"ru": "книголюб",
"ex": "The bookworm read three books yesterday.",
"g": "Text",
"gru": "Слова текста · Ex.2–4",
"star": false,
"idiom": false
},
{
"k": "g3",
"en": "brilliant",
"def": "Very clever or very good at something.",
"ru": "блестящий; очень умный",
"ex": "The brilliant detective found the missing sandwich.",
"g": "Text",
"gru": "Слова текста · Ex.2–4",
"star": true,
"idiom": false
},
{
"k": "g4",
"en": "cape",
"def": "Clothing worn over the shoulders.",
"ru": "плащ; накидка",
"ex": "The cat wore a cape to the library.",
"g": "Text",
"gru": "Слова текста · Ex.2–4",
"star": true,
"idiom": false
},
{
"k": "g5",
"en": "clever",
"def": "Able to learn and understand things quickly.",
"ru": "умный",
"ex": "The clever fox solved the puzzle.",
"g": "Text",
"gru": "Слова текста · Ex.2–4",
"star": true,
"idiom": false
},
{
"k": "g6",
"en": "comedy",
"def": "A funny play, film or story.",
"ru": "комедия",
"ex": "The comedy made the robots laugh.",
"g": "Genres",
"gru": "Жанры · Ex.1",
"star": false,
"idiom": false
},
{
"k": "g7",
"en": "companion",
"def": "Someone who goes with you.",
"ru": "спутник; товарищ",
"ex": "The detective travelled with a companion.",
"g": "Text",
"gru": "Слова текста · Ex.2–4",
"star": false,
"idiom": false
},
{
"k": "g8",
"en": "crime",
"def": "An action that breaks the law.",
"ru": "преступление",
"ex": "Someone stole a sandwich. It was a crime.",
"g": "Text",
"gru": "Слова текста · Ex.2–4",
"star": false,
"idiom": false
},
{
"k": "g9",
"en": "criminal",
"def": "Someone who commits a crime.",
"ru": "преступник",
"ex": "The criminal left sandwich crumbs.",
"g": "Text",
"gru": "Слова текста · Ex.2–4",
"star": false,
"idiom": false
},
{
"k": "g10",
"en": "dangerous",
"def": "Something that can hurt you.",
"ru": "опасный",
"ex": "The robot avoided a dangerous cactus.",
"g": "Text",
"gru": "Слова текста · Ex.2–4",
"star": false,
"idiom": false
},
{
"k": "g11",
"en": "detective",
"def": "Someone who finds out who committed a crime.",
"ru": "детектив; сыщик",
"ex": "The detective found tiny pawprints.",
"g": "Text",
"gru": "Слова текста · Ex.2–4",
"star": false,
"idiom": false
},
{
"k": "g12",
"en": "emotional",
"def": "Showing strong feelings.",
"ru": "эмоциональный",
"ex": "The emotional robot cried at the story.",
"g": "Text",
"gru": "Слова текста · Ex.2–4",
"star": false,
"idiom": false
},
{
"k": "g13",
"en": "event",
"def": "Something that happens.",
"ru": "событие",
"ex": "The book fair was a great event.",
"g": "Text",
"gru": "Слова текста · Ex.2–4",
"star": false,
"idiom": false
},
{
"k": "g14",
"en": "excitement",
"def": "A strong happy or eager feeling.",
"ru": "волнение; возбуждение",
"ex": "The cat jumped with excitement.",
"g": "Text",
"gru": "Слова текста · Ex.2–4",
"star": false,
"idiom": false
},
{
"k": "g15",
"en": "extraordinary",
"def": "Very unusual or amazing.",
"ru": "необыкновенный",
"ex": "The octopus had extraordinary reading skills.",
"g": "Text",
"gru": "Слова текста · Ex.2–4",
"star": true,
"idiom": false
},
{
"k": "g16",
"en": "faithful",
"def": "Loyal to someone.",
"ru": "верный",
"ex": "The faithful dog helped the detective.",
"g": "Text",
"gru": "Слова текста · Ex.2–4",
"star": true,
"idiom": false
},
{
"k": "g17",
"en": "fairy tale",
"def": "A story with magic and imaginary creatures.",
"ru": "сказка",
"ex": "The fairy tale had a magic castle.",
"g": "Genres",
"gru": "Жанры · Ex.1",
"star": false,
"idiom": false
},
{
"k": "g18",
"en": "famous",
"def": "Known by many people.",
"ru": "знаменитый",
"ex": "The famous cat signed a book.",
"g": "Text",
"gru": "Слова текста · Ex.2–4",
"star": true,
"idiom": false
},
{
"k": "g19",
"en": "fictional",
"def": "Invented for a story; not a real person or event.",
"ru": "вымышленный",
"ex": "The dragon was a fictional character.",
"g": "Text",
"gru": "Слова текста · Ex.2–4",
"star": false,
"idiom": false
},
{
"k": "g20",
"en": "funny",
"def": "Making you laugh.",
"ru": "смешной",
"ex": "The funny robot wore a saucepan.",
"g": "Text",
"gru": "Слова текста · Ex.2–4",
"star": false,
"idiom": false
},
{
"k": "g21",
"en": "gossip",
"def": "To talk about other people’s private lives.",
"ru": "сплетничать",
"ex": "The cats liked to gossip about books.",
"g": "Text",
"gru": "Слова текста · Ex.2–4",
"star": false,
"idiom": false
},
{
"k": "g22",
"en": "great",
"def": "Very good or important.",
"ru": "замечательный; великий",
"ex": "The author wrote a great story.",
"g": "Text",
"gru": "Слова текста · Ex.2–4",
"star": false,
"idiom": false
},
{
"k": "g23",
"en": "history",
"def": "Past events, or the study of them.",
"ru": "история",
"ex": "The cat studied the history of castles.",
"g": "Genres",
"gru": "Жанры · Ex.1",
"star": false,
"idiom": false
},
{
"k": "g24",
"en": "humorous",
"def": "Funny and amusing.",
"ru": "юмористический",
"ex": "The humorous story made us laugh.",
"g": "Text",
"gru": "Слова текста · Ex.2–4",
"star": false,
"idiom": false
},
{
"k": "g25",
"en": "imagination",
"def": "The ability to make pictures and ideas in your mind.",
"ru": "воображение",
"ex": "The author had a great imagination.",
"g": "Text",
"gru": "Слова текста · Ex.2–4",
"star": true,
"idiom": false
},
{
"k": "g26",
"en": "inspire",
"def": "To give someone an idea to create something.",
"ru": "вдохновлять",
"ex": "The submarine can inspire a new story.",
"g": "Text",
"gru": "Слова текста · Ex.2–4",
"star": true,
"idiom": false
},
{
"k": "g27",
"en": "intelligent",
"def": "Clever; able to understand things well.",
"ru": "умный",
"ex": "The intelligent owl solved the puzzle.",
"g": "Text",
"gru": "Слова текста · Ex.2–4",
"star": true,
"idiom": false
},
{
"k": "g28",
"en": "investigation",
"def": "Work to find out the truth about a crime.",
"ru": "расследование",
"ex": "The investigation found the missing lunch.",
"g": "Text",
"gru": "Слова текста · Ex.2–4",
"star": true,
"idiom": false
},
{
"k": "g29",
"en": "loyal",
"def": "Supporting someone and not leaving them.",
"ru": "преданный; верный",
"ex": "The loyal robot helped its friend.",
"g": "Text",
"gru": "Слова текста · Ex.2–4",
"star": true,
"idiom": false
},
{
"k": "g30",
"en": "magnifying glass",
"def": "A lens that makes things look bigger.",
"ru": "увеличительное стекло",
"ex": "The detective used a magnifying glass.",
"g": "Text",
"gru": "Слова текста · Ex.2–4",
"star": true,
"idiom": false
},
{
"k": "g31",
"en": "mysterious",
"def": "Strange and difficult to explain.",
"ru": "таинственный",
"ex": "The cat found a mysterious door.",
"g": "Text",
"gru": "Слова текста · Ex.2–4",
"star": false,
"idiom": false
},
{
"k": "g32",
"en": "myth",
"def": "An old traditional story, often about gods or heroes.",
"ru": "миф",
"ex": "The myth told a story about a dragon.",
"g": "Genres",
"gru": "Жанры · Ex.1",
"star": false,
"idiom": false
},
{
"k": "g33",
"en": "neat",
"def": "Clean, tidy and carefully arranged.",
"ru": "аккуратный",
"ex": "The detective had a neat appearance.",
"g": "Text",
"gru": "Слова текста · Ex.2–4",
"star": true,
"idiom": false
},
{
"k": "g34",
"en": "novel",
"def": "A long story in a book.",
"ru": "роман",
"ex": "The cat read a long novel.",
"g": "Genres",
"gru": "Жанры · Ex.1",
"star": false,
"idiom": false
},
{
"k": "g35",
"en": "obsession",
"def": "Something you think about all the time.",
"ru": "навязчивая идея",
"ex": "Sandwiches became the cat’s obsession.",
"g": "Text",
"gru": "Слова текста · Ex.2–4",
"star": true,
"idiom": false
},
{
"k": "g36",
"en": "order",
"def": "Things arranged neatly and correctly.",
"ru": "порядок",
"ex": "The robot put the books in order.",
"g": "Text",
"gru": "Слова текста · Ex.2–4",
"star": true,
"idiom": false
},
{
"k": "g37",
"en": "ordinary",
"def": "Normal; not unusual or special.",
"ru": "обычный",
"ex": "It was an ordinary cup of tea.",
"g": "Text",
"gru": "Слова текста · Ex.2–4",
"star": true,
"idiom": false
},
{
"k": "g38",
"en": "poem",
"def": "Writing in short lines, often with rhythm.",
"ru": "стихотворение",
"ex": "The cat wrote a poem about lunch.",
"g": "Genres",
"gru": "Жанры · Ex.1",
"star": false,
"idiom": false
},
{
"k": "g39",
"en": "psychology",
"def": "The study of the mind and behaviour.",
"ru": "психология",
"ex": "The owl studied psychology.",
"g": "Text",
"gru": "Слова текста · Ex.2–4",
"star": true,
"idiom": false
},
{
"k": "g40",
"en": "quiz",
"def": "A short set of questions.",
"ru": "викторина",
"ex": "The robots did a quiz about books.",
"g": "Text",
"gru": "Слова текста · Ex.2–4",
"star": false,
"idiom": false
},
{
"k": "g41",
"en": "several",
"def": "More than two, but not many.",
"ru": "несколько",
"ex": "The cat borrowed several books.",
"g": "Text",
"gru": "Слова текста · Ex.2–4",
"star": true,
"idiom": false
},
{
"k": "g42",
"en": "strange",
"def": "Unusual; difficult to understand.",
"ru": "странный",
"ex": "A strange teapot walked into the room.",
"g": "Text",
"gru": "Слова текста · Ex.2–4",
"star": true,
"idiom": false
},
{
"k": "g43",
"en": "tidy",
"def": "With everything in the right place.",
"ru": "опрятный; аккуратный",
"ex": "The robot kept its room tidy.",
"g": "Text",
"gru": "Слова текста · Ex.2–4",
"star": false,
"idiom": false
},
{
"k": "g44",
"en": "typical",
"def": "Usual for this kind of person or thing.",
"ru": "типичный; обычный",
"ex": "Sherlock is not a typical student.",
"g": "Text",
"gru": "Слова текста · Ex.2–4",
"star": true,
"idiom": false
},
{
"k": "g45",
"en": "underwater",
"def": "Below the surface of water.",
"ru": "подводный; под водой",
"ex": "The robot took an underwater photo.",
"g": "Text",
"gru": "Слова текста · Ex.2–4",
"star": true,
"idiom": false
},
{
"k": "g46",
"en": "unusual",
"def": "Different from what is normal.",
"ru": "необычный",
"ex": "The cat found an unusual apple.",
"g": "Text",
"gru": "Слова текста · Ex.2–4",
"star": true,
"idiom": false
},
{
"k": "g47",
"en": "well known",
"def": "Famous; known by many people.",
"ru": "известный",
"ex": "The writer was well known.",
"g": "Text",
"gru": "Слова текста · Ex.2–4",
"star": true,
"idiom": false
},
{
"k": "g48",
"en": "writer",
"def": "A person who writes books or stories.",
"ru": "писатель",
"ex": "The writer created a talking robot.",
"g": "Text",
"gru": "Слова текста · Ex.2–4",
"star": false,
"idiom": false
},
{
"k": "g49",
"en": "a suspense story",
"def": "A story that makes you wonder what will happen next.",
"ru": "история, держащая в напряжении",
"ex": "The suspense story kept us guessing.",
"g": "Genres",
"gru": "Жанры · Ex.1",
"star": false,
"idiom": false
},
{
"k": "g50",
"en": "at first glance",
"def": "The first time you look at someone or something.",
"ru": "на первый взгляд",
"ex": "At first glance, the cat looked ordinary.",
"g": "Text",
"gru": "Слова текста · Ex.2–4",
"star": true,
"idiom": false
},
{
"k": "g51",
"en": "solve the mystery case",
"def": "To find the answer to a mysterious crime.",
"ru": "раскрыть загадочное дело",
"ex": "The detective tried to solve the mystery case.",
"g": "Text",
"gru": "Слова текста · Ex.2–4",
"star": true,
"idiom": false
}
];
